pipeline {
    agent any
    parameters {
        string(name: 'VERSION', defaultValue: '', description: 'Version for Docker images')
    }

    stages{
        stage("Git Checkout"){
            steps{
                echo "Cloning Repo"
                checkout scm
                echo "${params.VERSION}"
                echo "Cloning Successfull"
            }
        }
        stage("Update Manifest"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                        sed -i -e s/wanderlust-backend.*/wanderlust-backend:${params.VERSION}/g backend.yaml
                        """    
                    }
                    dir('kubernetes'){
                        sh """
                        sed -i -e s/wanderlust-frontend.*/wanderlust-frontend:${params.VERSION}/g frontend.yaml
                        """    
                    }
                }
            }
        }
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'GitHub-Creds',varibable:'GITHUB_TOKEN' gitToolName: 'git-tool')]) {
                        sh '''
                        echo "Configuring Git user"
                        git config --global user.email "gauravtayade1192@gmail.com"
                        git config --global user.name "Gaurav Tayade"

                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated environment variables"
                        
                        echo "Pushing changes to github: "
                        // git push origin 1.0.x
                        git push https://${GITHUB_TOKEN}@github.com/gauravtayade11/wanderlust-project HEAD:1.0.x
                    '''
                    }
                }
            }
        }
    }
}
